In [ ]:
from google.colab import files
import pandas as pd

In [ ]:
files.upload()

In [ ]:
df=pd.read_csv("cleaned_numpy_data.csv")

In [ ]:
df=pd.DataFrame(df)

In [ ]:
df=df.rename(columns={'0':'age','1':'income','2':'ownership','3':'emp','4':'intend','5':'grade','6':'amount','7':'intrest','8':'status','9':'percent','10':'default','11':'history'})

In [ ]:
df.head()

,age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history
0,22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.593220,Y,3.0
1,21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.104167,N,2.0
2,25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.572917,N,3.0
3,23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.534351,N,2.0
4,24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.643382,Y,4.0

In [ ]:
#checking types and unique values
print(df.dtypes)
print(df['intend'].unique())
print(df['grade'].unique())
print(df['ownership'].unique())
print(df['emp'].unique())
print(df['default'].unique())

age          float64
income       float64
ownership     object
emp          float64
intend        object
grade         object
amount       float64
intrest      float64
status       float64
percent      float64
default       object
history      float64
dtype: object
['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']
['D' 'B' 'C' 'A' 'E' 'F' 'G']
['RENT' 'OWN' 'MORTGAGE' 'OTHER']
[123.   5.   1.   4.   8.   2.   6.   7.   0.   9.   3.  10.  11.  18.
  12.  17.  14.  16.  13.  19.  15.  20.  22.  21.  24.  23.  26.  25.
  27.  28.  31.  41.  34.  29.  38.  30.]
['Y' 'N']

In [ ]:
#check for missing values
df.select_dtypes(include='object').isna().sum()

ownership    0
intend       0
grade        0
default      0
dtype: int64

In [ ]:
#have to check for potential outliers in income
print(f"max income:{df['income'].max()} ; min income:{df['income'].min()}")
print(f"mean of income:{df['income'].mean()} ; median of income:{df['income'].median()}")
#we can see mean>median hence its right skewed so outliers exist

max income:225200.0 ; min income:4000.0
mean of income:64335.810625824866 ; median of income:55000.0

In [ ]:
q1= df['income'].quantile(0.25)
q3= df['income'].quantile(0.75)
iqr= q3-q1
lower_bound= q1-1.5*iqr
upper_bound= q3+1.5*iqr
print(f"lower bound:{lower_bound} ; upper bound:{upper_bound}")

lower bound:-22550.0 ; upper bound:140250.0

In [ ]:
df['income'].quantile(0.99)
#we have 99th place of data which can be used to deal with outlier as it is more higher than upper bound

np.float64(225040.00000000015)

In [ ]:
df['income']=df['income'].clip(upper=df['income'].quantile(0.99))

In [ ]:
print(f"max income:{df['income'].max()} ; min income:{df['income'].min()}")
print(f"mean of income:{df['income'].mean()} ; median of income:{df['income'].median()}")

max income:225040.0000000003 ; min income:4000.0
mean of income:64334.209692765726 ; median of income:55000.0

In [ ]:
df.to_csv('cleaned_pandas_dataaa.csv', index=False)

In [ ]:
files.download('cleaned_pandas_dataaa.csv')