In [1]:
from google.colab import files
import pandas as pd

In [2]:
files.upload()

Saving cleaned_pandas_dataaa.csv to cleaned_pandas_dataaa.csv

{'cleaned_pandas_dataaa.csv': b'age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history\n22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.5932203389830508,Y,3.0\n21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.1041666666666666,N,2.0\n25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.5729166666666666,N,3.0\n23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.5343511450381679,N,2.0\n24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.6433823529411765,Y,4.0\n21.0,9900.0,OWN,2.0,VENTURE,A,2500.0,7.14,1.0,0.2525252525252525,N,2.0\n26.0,77100.0,RENT,8.0,EDUCATION,B,35000.0,12.42,1.0,0.4539559014267185,N,3.0\n24.0,78956.0,RENT,5.0,MEDICAL,B,35000.0,11.11,1.0,0.443284867521151,N,4.0\n24.0,83000.0,RENT,8.0,PERSONAL,A,35000.0,8.9,1.0,0.4216867469879518,N,2.0\n21.0,10000.0,OWN,6.0,VENTURE,D,1600.0,14.74,1.0,0.16,N,3.0\n22.0,85000.0,RENT,6.0,VENTURE,B,35000.0,10.37,1.0,0.4117647058823529,N,4.0\n21.0,10000.0,OWN,2.0,HOMEIMPROVEMENT,A,4500.0,8.63,1.0,0.45,N,2.0\n23.0,95000.0,RENT,2.0,VENTURE,A,35000.0,7.9,1.0,0.3684210526315789,N,2.0\n26.0,108160.0,RENT,4.0,EDUCATION,E,35000.0,18.39,1.0,0.323594674556213,N,4.0\n23.0,115000.0,RENT,2.0,EDUCATION,A,35000.0,7.9,0.0,0.3043478260869565,N,4.0\n23.0,225200.0,MORTGAGE,7.0,DEBTCONSOLIDATION,B,30000.0,10.65,0.0,0.1332149200710479,N,3.0\n23.0,120000.0,RENT,0.0,EDUCATION,A,35000.0,7.9,0.0,0.2916666666666667,N,4.0\n23.0,92111.0,RENT,7.0,MEDICAL,F,35000.0,20.25,1.0,0.3799763329026935,N,4.0\n23.0,113000.0,RENT,8.0,DEBTCONSOLIDATION,D,35000.0,18.25,1.0,0.3097345132743362,N,4.0\n24.0,10800.0,MORTGAGE,8.0,EDUCATION,B,1750.0,10.99,1.0,0.162037037037037,N,2.0\n25.0,162500.0,RENT,2.0,VENTURE,A,35000.0,7.49,0.0,0.2153846153846154,N,4.0\n25.0,137000.0,RENT,9.0,PERSONAL,E,34800.0,16.77,0.0,0.2540145985401459,Y,2.0\n22.0,65000.0,RENT,4.0,EDUCATION,D,34000.0,17.58,1.0,0.5230769230769231,N,4.0\n24.0,10980.0,OWN,0.0,PERSONAL,A,1500.0,7.29,0.0,0.1366120218579235,N,3.0\n22.0,80000.0,RENT,3.0,PERSONAL,D,33950.0,14.54,1.0,0.424375,Y,4.0\n24.0,67746.0,RENT,8.0,HOMEIMPROVEMENT,C,33000.0,12.68,1.0,0.4871136303250376,N,3.0\n21.0,11000.0,MORTGAGE,3.0,VENTURE,E,4575.0,17.74,1.0,0.4159090909090909,Y,3.0\n23.0,11000.0,OWN,0.0,PERSONAL,A,1400.0,9.32,0.0,0.1272727272727272,N,3.0\n24.0,65000.0,RENT,6.0,HOMEIMPROVEMENT,B,32500.0,9.99,1.0,0.5,N,3.0\n21.0,11389.0,OTHER,5.0,EDUCATION,C,4000.0,12.84,1.0,0.3512160856967249,Y,2.0\n21.0,11520.0,OWN,5.0,MEDICAL,B,2000.0,11.12,1.0,0.1736111111111111,N,3.0\n25.0,120000.0,RENT,2.0,VENTURE,A,32000.0,6.62,0.0,0.2666666666666666,N,2.0\n26.0,95000.0,RENT,7.0,HOMEIMPROVEMENT,C,31050.0,14.17,1.0,0.3268421052631579,Y,3.0\n25.0,225200.0,RENT,2.0,DEBTCONSOLIDATION,C,24250.0,13.85,0.0,0.1076820603907637,N,3.0\n26.0,225200.0,MORTGAGE,10.0,MEDICAL,C,7800.0,13.49,0.0,0.0346358792184724,N,4.0\n21.0,12000.0,OWN,5.0,EDUCATION,A,2500.0,7.51,1.0,0.2083333333333333,N,4.0\n22.0,48000.0,RENT,1.0,EDUCATION,E,30000.0,18.39,1.0,0.625,N,2.0\n24.0,64000.0,RENT,8.0,DEBTCONSOLIDATION,D,30000.0,14.54,1.0,0.46875,Y,3.0\n25.0,75000.0,RENT,4.0,HOMEIMPROVEMENT,D,30000.0,16.89,1.0,0.4,Y,4.0\n23.0,71500.0,RENT,3.0,DEBTCONSOLIDATION,D,30000.0,10.99,1.0,0.4195804195804196,N,4.0\n26.0,62050.0,RENT,6.0,MEDICAL,E,30000.0,17.99,1.0,0.48348106365834,N,2.0\n24.0,12000.0,OWN,4.0,VENTURE,B,2500.0,12.69,1.0,0.2083333333333333,N,3.0\n26.0,225200.0,MORTGAGE,10.0,VENTURE,A,20000.0,7.88,0.0,0.0888099467140319,N,4.0\n23.0,225200.0,OWN,1.0,EDUCATION,F,24250.0,19.41,0.0,0.1076820603907637,Y,2.0\n26.0,225200.0,OWN,9.0,HOMEIMPROVEMENT,B,10000.0,10.38,0.0,0.0444049733570159,N,4.0\n26.0,225200.0,MORTGAGE,0.0,EDUCATION,D,25000.0,15.33,0.0,0.1110124333925399,N,3.0\n25.0,225200.0,MORTGAGE,9.0,HOMEIMPROVEMENT,E,18000.0,16.45,0.0,0.0799289520426287,N,3.0\n26.0,80690.0,RENT,8.0,PERSONAL,A,30000.0,7.49,1.0,0.3717932829346883,N,3.0\n22.0,66300.0,RENT,4.0,MEDICAL,B,30000.0,12.69,1.0,0.4524886877828054,N,3.0\n26.0,89028.0,RENT,0.0,DEBTCONSOLIDATION,A,30000.0,6.62,1.0,0.3369726378218088,N,3.0\n24.0,78000.0,RENT,4.0,DEBTCONSOLIDATION,D,30000.0,10.99,1.0,0.3846153846153846,Y,4.0\n23.0,78000.0,RENT,7.0,DEBTCONSOLIDATION,F,30000.0,18.62,1.0,0.3846153846153846,Y,3.0\n23.0,92004.0,RENT,6.0,PERSONAL,C,30000.0,15.23,1.0,0.3260727794443719,Y,3.0\n23.0,97000.0,RENT,7.0,VENTURE,B,30000.0,10.65,1.0,0.3092783505154639,N,2.0\n25.0,120000.0,RENT,9.0,EDUCATION,A,30000.0,7.9,0.0,0.25,N,4.0\n26.0,225200.0,RENT,4.0,PERSONAL,C,10000.0,15.96,0.0,0.0444049733570159,Y,3.0\n26.0,225200.0,RENT,0.0,VENTURE,B,20000.0,11.48,0.0,0.0888099467140319,N,3.0\n23.0,225200.0,OWN,3.0,PERSONAL,A,35000.0,10.99,0.0,0.1554174067495559,N,4.0\n25.0,128000.0,RENT,9.0,PERSONAL,A,30000.0,7.29,0.0,0.234375,N,4.0\n24.0,12000.0,OWN,2.0,VENTURE,E,1750.0,10.99,0.0,0.1458333333333333,Y,3.0\n21.0,131000.0,RENT,0.0,VENTURE,A,30000.0,5.99,0.0,0.2290076335877862,N,4.0\n22.0,225200.0,OWN,6.0,VENTURE,B,12000.0,11.58,0.0,0.0532859680284191,N,2.0\n26.0,225200.0,MORTGAGE,0.0,EDUCATION,B,10000.0,10.99,1.0,0.0444049733570159,N,4.0\n25.0,221850.0,MORTGAGE,9.0,MEDICAL,D,25000.0,15.7,1.0,0.1126887536623845,N,2.0\n22.0,70000.0,RENT,6.0,EDUCATION,D,29100.0,15.99,1.0,0.4157142857142857,N,3.0\n22.0,12000.0,MORTGAGE,7.0,EDUCATION,D,1500.0,14.84,0.0,0.125,Y,3.0\n26.0,225200.0,OWN,10.0,HOMEIMPROVEMENT,B,28000.0,10.99,0.0,0.1243339253996447,N,3.0\n25.0,225200.0,MORTGAGE,9.0,HOMEIMPROVEMENT,D,20000.0,14.42,0.0,0.0888099467140319,Y,2.0\n24.0,225200.0,MORTGAGE,9.0,EDUCATION,A,9600.0,6.99,0.0,0.0426287744227353,N,2.0\n25.0,225200.0,RENT,2.0,MEDICAL,C,25000.0,13.49,0.0,0.1110124333925399,N,4.0\n25.0,12000.0,OWN,0.0,MEDICAL,C,3000.0,10.99,1.0,0.25,N,3.0\n22.0,56950.0,RENT,6.0,MEDICAL,A,28000.0,10.99,1.0,0.4916593503072871,N,2.0\n21.0,12000.0,OWN,6.0,EDUCATION,C,3000.0,13.61,1.0,0.25,Y,3.0\n23.0,65000.0,RENT,2.0,EDUCATION,A,28000.0,7.9,1.0,0.4307692307692308,N,2.0\n26.0,85000.0,RENT,2.0,VENTURE,A,28000.0,7.49,1.0,0.3294117647058823,N,3.0\n26.0,12000.0,OWN,2.0,EDUCATION,A,6100.0,7.51,1.0,0.5083333333333333,N,3.0\n22.0,88000.0,RENT,6.0,VENTURE,B,28000.0,9.91,1.0,0.3181818181818182,N,3.0\n21.0,12000.0,OWN,0.0,PERSONAL,C,4200.0,13.48,1.0,0.35,Y,4.0\n22.0,12000.0,OWN,6.0,DEBTCONSOLIDATION,A,4750.0,7.14,1.0,0.3958333333333333,N,2.0\n24.0,83004.0,RENT,0.0,VENTURE,D,28000.0,15.99,1.0,0.3373331405715387,Y,4.0\n24.0,225200.0,RENT,2.0,EDUCATION,C,18000.0,12.98,0.0,0.0799289520426287,Y,3.0\n26.0,225200.0,RENT,4.0,VENTURE,C,4800.0,13.57,0.0,0.0213143872113676,N,3.0\n25.0,100000.0,RENT,5.0,DEBTCONSOLIDATION,B,28000.0,12.69,0.0,0.28,N,3.0\n26.0,110000.0,RENT,10.0,EDUCATION,A,28000.0,8.9,0.0,0.2545454545454545,N,2.0\n26.0,12000.0,OWN,0.0,DEBTCONSOLIDATION,A,2700.0,10.99,1.0,0.225,N,4.0\n22.0,108000.0,RENT,6.0,EDUCATION,B,28000.0,10.99,1.0,0.2592592592592592,N,4.0\n23.0,151200.0,RENT,7.0,DEBTCONSOLIDATION,B,28000.0,11.11,0.0,0.1851851851851851,N,2.0\n24.0,69000.0,RENT,2.0,HOMEIMPROVEMENT,A,27600.0,10.99,1.0,0.4,N,2.0\n21.0,12000.0,MORTGAGE,5.0,DEBTCONSOLIDATION,E,3250.0,15.68,1.0,0.2708333333333333,Y,3.0\n22.0,70000.0,RENT,4.0,EDUCATION,C,27500.0,13.06,1.0,0.3928571428571428,Y,3.0\n22.0,225200.0,OWN,6.0,PERSONAL,B,25000.0,10.99,0.0,0.1110124333925399,N,2.0\n26.0,73200.0,RENT,5.0,VENTURE,D,27050.0,15.62,1.0,0.369535519125683,Y,2.0\n24.0,83000.0,RENT,5.0,PERSONAL,C,27000.0,13.49,1.0,0.3253012048192771,Y,2.0\n24.0,73399.0,RENT,0.0,VENTURE,D,27000.0,10.99,1.0,0.3678524230575348,N,3.0\n23.0,62500.0,RENT,7.0,MEDICAL,B,26000.0,11.71,1.0,0.416,N,2.0\n23.0,120000.0,RENT,1.0,EDUCATION,B,25600.0,12.69,0.0,0.2133333333333333,N,3.0\n24.0,12360.0,OWN,2.0,MEDICAL,C,1600.0,13.57,0.0,0.1294498381877022,N,3.0\n22.0,60000.0,RENT,0.0,VENTURE,B,25475.0,10.99,1.0,0.4245833333333333,N,3.0\n25.0,225200.0,MORTGAGE,3.0,MEDICAL,C,20000.0,14.27,0.0,0.0888099467140319,Y,4.0\n24.0,225200.0,OWN,8.0,HOMEIMPROVEMENT,B,20000.0,8.88,0.0,0.0888099467140319,N,4.0\n26.0,225200.0,MORTGAGE,10.0,HOMEIMPROVEMENT,B,21600.0,12.18,0.0,0.0959147424511545,N,3.0\n25.0,221004.0,MORTGAGE,6.0,DEBTCONSOLIDATION,D,11900.0,14.42,1.0,0.0538451792727733,Y,3.0\n26.0,225200.0,MORTGAGE,0.0,MEDICAL,C,25000.0,14.17,0.0,0.1110124333925399,Y,2.0\n25.0,225200.0,MORTGAGE,5.0,MEDICAL,C,35000.0,13.99,0.0,0.1554174067495559,N,4.0\n23.0,83000.0,RENT,7.0,EDUCATION,B,25300.0,10.99,1.0,0.3048192771084337,N,3.0\n22.0,12600.0,MORTGAGE,4.0,PERSONAL,A,2000.0,5.42,1.0,0.1587301587301587,N,4.0\n25.0,12600.0,OWN,3.0,PERSONAL,C,1750.0,13.61,0.0,0.1388888888888889,N,3.0\n21.0,42500.0,RENT,3.0,EDUCATION,C,25000.0,12.73,1.0,0.5882352941176471,Y,3.0\n24.0,41000.0,RENT,2.0,HOMEIMPROVEMENT,D,25000.0,10.99,1.0,0.6097560975609756,N,3.0\n25.0,12816.0,OWN,0.0,DEBTCONSOLIDATION,C,3000.0,12.87,1.0,0.2340823970037453,Y,4.0\n24.0,12960.0,MORTGAGE,1.0,HOMEIMPROVEMENT,B,3650.0,9.91,1.0,0.2816358024691358,N,3.0\n26.0,225200.0,MORTGAGE,4.0,HOMEIMPROVEMENT,B,20000.0,11.49,0.0,0.0888099467140319,N,4.0\n25.0,225000.0,MORTGAGE,0.0,HOMEIMPROVEMENT,E,30000.0,19.91,0.0,0.1333333333333333,Y,2.0\n26.0,213000.0,MORTGAGE,6.0,EDUCATION,B,35000.0,10.65,1.0,0.1643192488262911,N,2.0\n24.0,225000.0,RENT,0.0,MEDICAL,B,6000.0,10.99,0.0,0.0266666666666666,N,4.0\n24.0,12960.0,MORTGAGE,0.0,DEBTCONSOLIDATION,B,4500.0,11.83,1.0,0.3472222222222222,N,4.0\n23.0,12996.0,OWN,0.0,DEBTCONSOLIDATION,C,2400.0,13.49,1.0,0.1846722068328716,Y,2.0\n22.0,42000.0,RENT,6.0,MEDICAL,D,25000.0,14.59,1.0,0.5952380952380952,Y,2.0\n26.0,48000.0,RENT,2.0,EDUCATION,B,25000.0,9.64,1.0,0.5208333333333334,N,4.0\n25.0,12996.0,OWN,1.0,MEDICAL,D,3600.0,14.59,1.0,0.2770083102493075,N,3.0\n22.0,12996.0,OWN,1.0,EDUCATION,B,4750.0,10.99,1.0,0.3654970760233918,N,3.0\n25.0,42360.0,RENT,1.0,EDUCATION,E,25000.0,16.35,1.0,0.5901794145420207,Y,3.0\n21.0,49000.0,RENT,4.0,EDUCATION,B,25000.0,10.99,1.0,0.5102040816326531,N,2.0\n25.0,225000.0,MORTGAGE,0.0,VENTURE,F,25000.0,18.67,0.0,0.1111111111111111,N,2.0\n26.0,225000.0,RENT,1.0,EDUCATION,A,3000.0,9.32,0.0,0.0133333333333333,N,4.0\n23.0,225000.0,RENT,8.0,DEBTCONSOLIDATION,A,7500.0,8.63,0.0,0.0333333333333333,N,2.0\n26.0,225000.0,MORTGAGE,2.0,VENTURE,B,25000.0,10.08,0.0,0.1111111111111111,N,2.0\n22.0,49464.0,RENT,5.0,PERSONAL,B,25000.0,11.83,1.0,0.5054180818372959,N,3.0\n23.0,50000.0,RENT,1.0,DEBTCONSOLIDATION,A,25000.0,7.9,1.0,0.5,N,3.0\n25.0,50000.0,RENT,4.0,HOMEIMPROVEMENT,A,25000.0,5.99,1.0,0.5,N,2.0\n24.0,44000.0,RENT,2.0,DEBTCONSOLIDATION,D,25000.0,15.33,1.0,0.5681818181818182,N,2.0\n23.0,50000.0,RENT,1.0,VENTURE,B,25000.0,11.83,1.0,0.5,N,4.0\n22.0,50004.0,RENT,0.0,VENTURE,B,25000.0,10.36,1.0,0.499960003199744,N,2.0\n22.0,50004.0,RENT,3.0,VENTURE,C,25000.0,12.23,1.0,0.499960003199744,N,3.0\n22.0,52000.0,RENT,2.0,EDUCATION,B,25000.0,11.11,1.0,0.4807692307692308,N,4.0\n23.0,13200.0,OWN,3.0,DEBTCONSOLIDATION,A,4950.0,7.9,1.0,0.375,N,4.0\n24.0,220000.0,MORTGAGE,1.0,EDUCATION,B,25000.0,11.58,0.0,0.1136363636363636,N,2.0\n23.0,216000.0,MORTGAGE,5.0,DEBTCONSOLIDATION,A,21000.0,8.9,0.0,0.0972222222222222,N,3.0\n25.0,216000.0,MORTGAGE,2.0,EDUCATION,D,25000.0,16.07,0.0,0.1157407407407407,N,3.0\n26.0,216000.0,MORTGAGE,10.0,EDUCATION,C,20000.0,14.22,0.0,0.0925925925925925,Y,2.0\n23.0,215000.0,MORTGAGE,7.0,MEDICAL,C,35000.0,14.79,0.0,0.1627906976744186,Y,3.0\n26.0,215000.0,MORTGAGE,11.0,EDUCATION,A,12000.0,7.88,0.0,0.055813953488372,N,2.0\n23.0,52000.0,RENT,1.0,PERSONAL,C,25000.0,13.22,1.0,0.4807692307692308,N,2.0\n26.0,46000.0,RENT,2.0,DEBTCONSOLIDATION,D,25000.0,11.86,1.0,0.5434782608695652,N,4.0\n22.0,53000.0,RENT,5.0,EDUCATION,C,25000.0,13.43,1.0,0.4716981132075472,Y,4.0\n26.0,47000.0,RENT,0.0,HOMEIMPROVEMENT,D,25000.0,15.28,1.0,0.5319148936170213,Y,2.0\n23.0,47000.0,RENT,1.0,VENTURE,E,25000.0,17.93,1.0,0.5319148936170213,N,2.0\n23.0,13200.0,MORTGAGE,2.0,EDUCATION,B,1400.0,9.25,0.0,0.106060606060606,N,4.0\n21.0,13200.0,OWN,0.0,VENTURE,C,4500.0,12.98,1.0,0.3409090909090909,N,4.0\n22.0,210000.0,MORTGAGE,6.0,VENTURE,B,16000.0,10.62,0.0,0.0761904761904762,N,4.0\n26.0,210000.0,OWN,10.0,PERSONAL,B,22000.0,11.83,0.0,0.1047619047619047,N,4.0\n26.0,48000.0,RENT,5.0,VENTURE,F,25000.0,18.43,1.0,0.5208333333333334,N,2.0\n22.0,54996.0,RENT,6.0,EDUCATION,B,25000.0,10.99,1.0,0.4545785148010764,N,4.0\n24.0,55000.0,RENT,4.0,HOMEIMPROVEMENT,D,25000.0,10.99,1.0,0.4545454545454545,Y,4.0\n23.0,55000.0,RENT,4.0,EDUCATION,B,25000.0,11.36,1.0,0.4545454545454545,N,3.0\n23.0,55000.0,RENT,4.0,EDUCATION,D,25000.0,15.65,1.0,0.4545454545454545,Y,3.0\n24.0,55164.0,RENT,8.0,PERSONAL,C,25000.0,13.22,1.0,0.4531941121020956,Y,4.0\n26.0,56000.0,RENT,4.0,DEBTCONSOLIDATION,C,25000.0,12.87,1.0,0.4464285714285714,N,2.0\n24.0,203500.0,OWN,8.0,MEDICAL,C,20000.0,13.04,0.0,0.0982800982800982,N,3.0\n23.0,190000.0,MORTGAGE,5.0,EDUCATION,F,22000.0,17.58,1.0,0.1157894736842105,Y,3.0\n23.0,13920.0,OWN,2.0,PERSONAL,E,7750.0,17.04,1.0,0.5567528735632183,N,4.0\n24.0,60000.0,RENT,0.0,PERSONAL,B,25000.0,10.99,1.0,0.4166666666666667,N,3.0\n24.0,60000.0,RENT,2.0,PERSONAL,B,25000.0,11.11,1.0,0.4166666666666667,N,3.0\n26.0,54000.0,RENT,7.0,DEBTCONSOLIDATION,D,25000.0,14.83,1.0,0.4629629629629629,Y,2.0\n23.0,14000.0,OWN,2.0,DEBTCONSOLIDATION,D,4000.0,10.99,1.0,0.2857142857142857,N,3.0\n24.0,200000.0,RENT,8.0,MEDICAL,B,12000.0,12.69,0.0,0.06,N,2.0\n24.0,200000.0,MORTGAGE,8.0,HOMEIMPROVEMENT,C,12000.0,13.49,0.0,0.06,N,2.0\n21.0,200000.0,MORTGAGE,5.0,EDUCATION,C,16000.0,14.65,0.0,0.08,N,4.0\n25.0,54000.0,RENT,3.0,HOMEIMPROVEMENT,E,25000.0,16.82,1.0,0.4629629629629629,N,4.0\n23.0,60000.0,RENT,3.0,PERSONAL,C,25000.0,12.73,1.0,0.4166666666666667,N,3.0\n23.0,60000.0,RENT,7.0,PERSONAL,B,25000.0,10.25,1.0,0.4166666666666667,N,4.0\n21.0,60000.0,RENT,6.0,EDUCATION,B,25000.0,10.99,1.0,0.4166666666666667,N,4.0\n25.0,61959.0,RENT,9.0,MEDICAL,C,25000.0,12.73,1.0,0.4034926322245356,N,2.0\n22.0,56400.0,RENT,2.0,HOMEIMPROVEMENT,D,25000.0,14.96,1.0,0.4432624113475177,Y,3.0\n23.0,200000.0,MORTGAGE,7.0,EDUCATION,A,28000.0,10.99,0.0,0.14,N,2.0\n21.0,200000.0,MORTGAGE,2.0,DEBTCONSOLIDATION,C,25000.0,13.99,0.0,0.125,N,2.0\n24.0,200000.0,MORTGAGE,3.0,VENTURE,A,24000.0,7.49,0.0,0.12,N,4.0\n26.0,200000.0,MORTGAGE,4.0,EDUCATION,C,15000.0,14.79,0.0,0.075,N,3.0\n25.0,200000.0,MORTGAGE,2.0,DEBTCONSOLIDATION,B,15500.0,11.99,0.0,0.0775,N,2.0\n24.0,200000.0,RENT,8.0,EDUCATION,A,10000.0,8.49,0.0,0.05,N,4.0\n24.0,66000.0,RENT,3.0,EDUCATION,B,25000.0,9.91,1.0,0.3787878787878788,N,2.0\n22.0,66000.0,RENT,6.0,EDUCATION,C,25000.0,13.06,1.0,0.3787878787878788,Y,3.0\n22.0,200000.0,MORTGAGE,6.0,DEBTCONSOLIDATION,A,9000.0,6.17,0.0,0.045,N,4.0\n26.0,200000.0,MORTGAGE,4.0,EDUCATION,B,6000.0,11.86,0.0,0.03,N,2.0\n25.0,200000.0,RENT,5.0,EDUCATION,D,18000.0,16.32,0.0,0.09,N,3.0\n25.0,200000.0,MORTGAGE,2.0,VENTURE,B,12000.0,10.38,0.0,0.06,N,2.0\n25.0,200000.0,MORTGAGE,9.0,PERSONAL,C,23050.0,14.35,0.0,0.11525,N,3.0\n24.0,200000.0,MORTGAGE,8.0,DEBTCONSOLIDATION,B,20000.0,10.99,0.0,0.1,N,3.0\n24.0,60000.0,RENT,2.0,DEBTCONSOLIDATION,E,25000.0,10.99,1.0,0.4166666666666667,Y,2.0\n21.0,14400.0,OWN,0.0,HOMEIMPROVEMENT,B,3000.0,10.99,1.0,0.2083333333333333,N,4.0\n26.0,66996.0,RENT,10.0,PERSONAL,D,25000.0,15.21,1.0,0.373156606364559,Y,2.0\n23.0,67000.0,RENT,3.0,EDUCATION,A,25000.0,7.9,1.0,0.373134328358209,N,4.0\n24.0,67000.0,RENT,2.0,VENTURE,B,25000.0,10.99,1.0,0.373134328358209,N,3.0\n24.0,68000.0,RENT,5.0,PERSONAL,D,25000.0,14.09,1.0,0.3676470588235294,Y,3.0\n25.0,69000.0,RENT,9.0,PERSONAL,D,25000.0,17.49,1.0,0.3623188405797101,N,2.0\n25.0,200000.0,MORTGAGE,0.0,EDUCATION,B,12000.0,11.48,0.0,0.06,N,3.0\n26.0,188000.0,MORTGAGE,10.0,VENTURE,E,20000.0,17.74,1.0,0.1063829787234042,N,2.0\n26.0,200000.0,MORTGAGE,4.0,PERSONAL,C,3000.0,13.92,0.0,0.015,N,3.0\n25.0,69996.0,RENT,9.0,EDUCATION,D,25000.0,15.21,1.0,0.3571632664723698,N,3.0\n22.0,14400.0,OWN,2.0,MEDICAL,B,4000.0,10.99,1.0,0.2777777777777778,N,3.0\n24.0,70000.0,RENT,3.0,EDUCATION,B,25000.0,11.86,1.0,0.3571428571428571,N,4.0\n24.0,14400.0,OWN,5.0,PERSONAL,A,6000.0,7.49,1.0,0.4166666666666667,N,3.0\n24.0,56100.0,RENT,7.0,MEDICAL,D,25000.0,16.49,1.0,0.445632798573975,N,4.0\n25.0,66000.0,RENT,9.0,VENTURE,D,25000.0,15.33,1.0,0.3787878787878788,Y,2.0\n26.0,66000.0,RENT,3.0,HOMEIMPROVEMENT,B,25000.0,11.58,1.0,0.3787878787878788,N,4.0\n25.0,14400.0,OWN,7.0,EDUCATION,A,5375.0,5.79,1.0,0.3732638888888889,N,2.0\n25.0,72612.0,RENT,9.0,MEDICAL,C,25000.0,13.11,1.0,0.3442957086982868,N,2.0\n23.0,74000.0,RENT,3.0,MEDICAL,B,25000.0,10.36,1.0,0.3378378378378378,N,3.0\n25.0,75000.0,RENT,9.0,DEBTCONSOLIDATION,B,25000.0,10.36,1.0,0.3333333333333333,N,2.0\n24.0,192000.0,RENT,0.0,MEDICAL,C,22000.0,10.99,0.0,0.1145833333333333,Y,2.0\n21.0,192000.0,MORTGAGE,123.0,VENTURE,A,20000.0,6.54,0.0,0.1041666666666666,N,4.0\n25.0,191000.0,MORTGAGE,1.0,MEDICAL,B,10000.0,12.53,0.0,0.0523560209424083,N,4.0\n26.0,190300.0,MORTGAGE,5.0,PERSONAL,A,15000.0,10.99,0.0,0.0788229111928534,N,3.0\n22.0,190000.0,MORTGAGE,3.0,VENTURE,C,10000.0,10.99,0.0,0.0526315789473684,N,3.0\n24.0,75000.0,RENT,4.0,EDUCATION,B,25000.0,10.25,1.0,0.3333333333333333,N,4.0\n22.0,71000.0,RENT,1.0,EDUCATION,D,25000.0,15.95,1.0,0.352112676056338,Y,4.0\n26.0,190000.0,MORTGAGE,3.0,VENTURE,B,20000.0,12.18,0.0,0.1052631578947368,N,4.0\n23.0,189996.0,OWN,0.0,PERSONAL,B,24000.0,11.83,0.0,0.1263184488094486,N,3.0\n23.0,78000.0,RENT,7.0,DEBTCONSOLIDATION,C,25000.0,10.99,1.0,0.3205128205128205,Y,2.0\n23.0,78000.0,RENT,1.0,VENTURE,B,25000.0,10.62,1.0,0.3205128205128205,N,3.0\n23.0,78504.0,RENT,7.0,VENTURE,B,25000.0,10.74,1.0,0.3184551105676144,N,3.0\n25.0,186000.0,OWN,9.0,VENTURE,B,10000.0,10.25,0.0,0.053763440860215,N,4.0\n24.0,185000.0,MORTGAGE,4.0,EDUCATION,B,35000.0,12.42,0.0,0.1891891891891892,N,2.0\n25.0,185000.0,RENT,6.0,VENTURE,C,15000.0,15.27,0.0,0.081081081081081,N,2.0\n24.0,62050.0,RENT,8.0,MEDICAL,D,25000.0,15.33,1.0,0.40290088638195,Y,2.0\n23.0,79416.0,RENT,7.0,VENTURE,D,25000.0,15.21,1.0,0.3147980255867835,Y,2.0\n21.0,14400.0,OWN,4.0,VENTURE,C,6250.0,14.72,1.0,0.4340277777777778,N,2.0\n24.0,79631.0,RENT,8.0,PERSONAL,D,25000.0,15.7,1.0,0.3139480855445744,Y,2.0\n24.0,79632.0,RENT,0.0,EDUCATION,C,25000.0,13.35,1.0,0.3139441430580671,N,4.0\n21.0,14400.0,MORTGAGE,0.0,MEDICAL,C,1500.0,10.99,0.0,0.1041666666666666,N,4.0\n24.0,80000.0,RENT,6.0,EDUCATION,A,25000.0,6.62,1.0,0.3125,N,2.0\n26.0,80000.0,RENT,5.0,DEBTCONSOLIDATION,C,25000.0,13.61,1.0,0.3125,N,4.0\n22.0,185000.0,RENT,4.0,MEDICAL,B,25000.0,11.36,0.0,0.1351351351351351,N,2.0\n26.0,185000.0,OWN,10.0,PERSONAL,A,5000.0,7.68,0.0,0.027027027027027,N,2.0\n24.0,184992.0,RENT,7.0,HOMEIMPROVEMENT,D,22000.0,14.46,0.0,0.1189240615810413,Y,4.0\n23.0,184000.0,OWN,5.0,EDUCATION,B,2500.0,11.83,0.0,0.0135869565217391,N,2.0\n24.0,172000.0,MORTGAGE,6.0,DEBTCONSOLIDATION,C,20000.0,13.47,1.0,0.1162790697674418,Y,4.0\n24.0,183000.0,MORTGAGE,2.0,MEDICAL,B,20000.0,11.49,0.0,0.1092896174863388,N,3.0\n22.0,183000.0,MORTGAGE,3.0,EDUCATION,A,1000.0,10.99,0.0,0.0054644808743169,N,2.0\n25.0,182952.0,MORTGAGE,9.0,PERSONAL,A,15000.0,6.03,0.0,0.0819887183523547,N,3.0\n23.0,74004.0,RENT,7.0,DEBTCONSOLIDATION,E,25000.0,16.35,1.0,0.3378195773201448,N,4.0\n26.0,74004.0,RENT,10.0,DEBTCONSOLIDATION,D,25000.0,10.99,1.0,0.3378195773201448,Y,4.0\n25.0,81000.0,RENT,5.0,DEBTCONSOLIDATION,A,25000.0,7.29,1.0,0.3086419753086419,N,3.0\n23.0,81600.0,RENT,1.0,MEDICAL,B,25000.0,11.36,1.0,0.3063725490196078,N,3.0\n24.0,82000.0,RENT,8.0,VENTURE,B,25000.0,10.25,0.0,0.3048780487804878,N,2.0\n24.0,83000.0,RENT,5.0,EDUCATION,B,25000.0,11.12,0.0,0.3012048192771084,N,3.0\n24.0,83000.0,RENT,5.0,PERSONAL,D,25000.0,12.92,0.0,0.3012048192771084,Y,3.0\n24.0,180000.0,RENT,8.0,EDUCATION,E,18000.0,18.64,0.0,0.1,Y,4.0\n23.0,180000.0,MORTGAGE,8.0,PERSONAL,A,28000.0,7.51,0.0,0.1555555555555555,N,3.0\n23.0,14400.0,OWN,2.0,HOMEIMPROVEMENT,E,4000.0,16.7,1.0,0.2777777777777778,N,2.0\n22.0,14400.0,OWN,0.0,PERSONAL,B,2100.0,11.14,0.0,0.1458333333333333,N,4.0\n22.0,84500.0,RENT,6.0,PERSONAL,F,25000.0,18.3,0.0,0.2958579881656805,N,4.0\n24.0,85000.0,RENT,5.0,MEDICAL,B,25000.0,10.62,0.0,0.2941176470588235,N,4.0\n24.0,180000.0,MORTGAGE,7.0,VENTURE,B,14000.0,11.99,0.0,0.0777777777777777,N,2.0\n26.0,180000.0,MORTGAGE,2.0,VENTURE,B,12000.0,9.63,0.0,0.0666666666666666,N,4.0\n25.0,142800.0,MORTGAGE,9.0,MEDICAL,F,10000.0,18.25,1.0,0.0700280112044818,N,4.0\n23.0,14664.0,MORTGAGE,0.0,D

In [3]:
df=pd.read_csv("cleaned_pandas_dataaa.csv")

In [4]:
df.head()

,age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history
0,22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.593220,Y,3.0
1,21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.104167,N,2.0
2,25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.572917,N,3.0
3,23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.534351,N,2.0
4,24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.643382,Y,4.0

In [5]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (2.0.45)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.4)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Collecting jedi>=0.16 (from ipython->ipython-sql)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->ipython-sql) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 23.4 MB/s eta 0:00:00
Installing collected packages: jedi
Successfully installed jedi-0.19.2

In [6]:
import sqlite3
conn = sqlite3.connect("loan.db")
df.to_sql("loan_data", conn, if_exists="replace", index=False)

32581

In [7]:
pd.read_sql("SELECT COUNT(*) FROM loan_data", conn)

   COUNT(*)
0     32581

In [8]:
pd.read_sql("select * from loan_data limit 10",conn)

,age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history
0,22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.593220,Y,3.0
1,21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.104167,N,2.0
2,25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.572917,N,3.0
3,23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.534351,N,2.0
4,24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.643382,Y,4.0
5,21.0,9900.0,OWN,2.0,VENTURE,A,2500.0,7.14,1.0,0.252525,N,2.0
6,26.0,77100.0,RENT,8.0,EDUCATION,B,35000.0,12.42,1.0,0.453956,N,3.0
7,24.0,78956.0,RENT,5.0,MEDICAL,B,35000.0,11.11,1.0,0.443285,N,4.0
8,24.0,83000.0,RENT,8.0,PERSONAL,A,35000.0,8.90,1.0,0.421687,N,2.0
9,21.0,10000.0,OWN,6.0,VENTURE,D,1600.0,14.74,1.0,0.160000,N,3.0

In [9]:
#double checking the income outliers
pd.read_sql("select max(income), min(income), avg(income) from loan_data",conn)

   max(income)  min(income)   avg(income)
0     225200.0       4000.0  64335.810626

In [10]:
pd.read_sql("select ownership ,count(*) as count from loan_data group by ownership order by count desc",conn)

  ownership  count
0      RENT  16446
1  MORTGAGE  13444
2       OWN   2584
3     OTHER    107

In [11]:
cursor = conn.cursor()
cursor.execute("alter table loan_data add column cust_id int")
conn.commit()

In [12]:
cursor.execute("update loan_data set cust_id=rowid ")
conn.commit()

In [30]:
##we create a new column for risk factor
cursor.execute("alter table loan_data add column risk float")
conn.commit()

In [31]:
pd.read_sql("select * from loan_data limit 10",conn)

,age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history,cust_id,risk
0,22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.593220,Y,3.0,1,None
1,21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.104167,N,2.0,2,None
2,25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.572917,N,3.0,3,None
3,23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.534351,N,2.0,4,None
4,24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.643382,Y,4.0,5,None
5,21.0,9900.0,OWN,2.0,VENTURE,A,2500.0,7.14,1.0,0.252525,N,2.0,6,None
6,26.0,77100.0,RENT,8.0,EDUCATION,B,35000.0,12.42,1.0,0.453956,N,3.0,7,None
7,24.0,78956.0,RENT,5.0,MEDICAL,B,35000.0,11.11,1.0,0.443285,N,4.0,8,None
8,24.0,83000.0,RENT,8.0,PERSONAL,A,35000.0,8.90,1.0,0.421687,N,2.0,9,None
9,21.0,10000.0,OWN,6.0,VENTURE,D,1600.0,14.74,1.0,0.160000,N,3.0,10,None

#RISK CALCULATION

In [36]:
cursor.execute("""
update loan_data
set risk =
(
    -- default (25%)
    (case when "default" = 'Y' then 5 ELSE 1 end) * 0.25

    -- percent (25%)
  +(case
        when percent > 0.3 then 3
        when percent > 0.6 then 5
        else 1
    end) * 0.25

    -- grade (15%)
  + (case
        when grade = 'A' then 1
        when grade = 'B' then 2
        when grade = 'C' then 3
        when grade = 'D' then 4
        when grade = 'E' then 5
        when grade = 'F' then 6
        when grade = 'G' then 7
    end) * 0.15

    -- employment (10%)
  + (case
        when emp <= 2 then 4
        when emp <= 9 then 2
        else 1
    end) * 0.10

    -- ownership (10%)
  + (case
        when ownership = 'RENT' then 4
        when ownership = 'MORTGAGE' then 2
        else 1
    end) * 0.10

    -- history (10%)
  + (case
        when history < 2 then 5
        when history <= 7 then 3
        else 1
    end) * 0.10

    -- age (5%)
  + (case
        when age < 25 then 2
        when age <= 50 then 1
        when age <= 60 then 3
        else 4
    end) * 0.05

    -- status (5%)
  + (case
        when status = 1 then 3
        else 1
    end) * 0.05
);


""")
conn.commit()

In [37]:
pd.read_sql("select * from loan_data limit 10",conn)

,age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history,cust_id,risk
0,22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.593220,Y,3.0,1,3.65
1,21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.104167,N,2.0,2,1.55
2,25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.572917,N,3.0,3,2.55
3,23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.534351,N,2.0,4,2.60
4,24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.643382,Y,4.0,5,3.60
5,21.0,9900.0,OWN,2.0,VENTURE,A,2500.0,7.14,1.0,0.252525,N,2.0,6,1.70
6,26.0,77100.0,RENT,8.0,EDUCATION,B,35000.0,12.42,1.0,0.453956,N,3.0,7,2.40
7,24.0,78956.0,RENT,5.0,MEDICAL,B,35000.0,11.11,1.0,0.443285,N,4.0,8,2.45
8,24.0,83000.0,RENT,8.0,PERSONAL,A,35000.0,8.90,1.0,0.421687,N,2.0,9,2.30
9,21.0,10000.0,OWN,6.0,VENTURE,D,1600.0,14.74,1.0,0.160000,N,3.0,10,1.95

In [38]:
cursor.execute("""
update loan_data
set risk = risk*20
""")
conn.commit()

In [40]:
pd.read_sql("select * from loan_data limit 10",conn)

,age,income,ownership,emp,intend,grade,amount,intrest,status,percent,default,history,cust_id,risk
0,22.0,59000.0,RENT,123.0,PERSONAL,D,35000.0,16.02,1.0,0.593220,Y,3.0,1,73.0
1,21.0,9600.0,OWN,5.0,EDUCATION,B,1000.0,11.14,0.0,0.104167,N,2.0,2,31.0
2,25.0,9600.0,MORTGAGE,1.0,MEDICAL,C,5500.0,12.87,1.0,0.572917,N,3.0,3,51.0
3,23.0,65500.0,RENT,4.0,MEDICAL,C,35000.0,15.23,1.0,0.534351,N,2.0,4,52.0
4,24.0,54400.0,RENT,8.0,MEDICAL,C,35000.0,14.27,1.0,0.643382,Y,4.0,5,72.0
5,21.0,9900.0,OWN,2.0,VENTURE,A,2500.0,7.14,1.0,0.252525,N,2.0,6,34.0
6,26.0,77100.0,RENT,8.0,EDUCATION,B,35000.0,12.42,1.0,0.453956,N,3.0,7,48.0
7,24.0,78956.0,RENT,5.0,MEDICAL,B,35000.0,11.11,1.0,0.443285,N,4.0,8,49.0
8,24.0,83000.0,RENT,8.0,PERSONAL,A,35000.0,8.90,1.0,0.421687,N,2.0,9,46.0
9,21.0,10000.0,OWN,6.0,VENTURE,D,1600.0,14.74,1.0,0.160000,N,3.0,10,39.0

In [41]:
from google.colab import files
df = pd.read_sql("SELECT * FROM loan_data", conn)
df.to_csv('sql_loan_data.csv', index=False)
files.download("sql_loan_data.csv")